# Name: The name assigned to all of the frontend objects defined in this template.
name: producer
# Docker image ref
image: docker-registry.default.svc:5000/kafka/producer:1.0.2
# Number of replicas
replicas: 3
# Environment variables
env:
- name: BROKER_HOSTNAME
  value: kafka-kafka-headless
- name: BROKER_PORT
  value: "9092"
- name: TOPIC
  value: test1
- name: KEY
  value: testKey
