{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}-ui
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - name: ui
    port: 9000
  selector:
    app: {{ include "kafka.name" . | quote }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name | quote }}
{{- end }}
