{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "kafka.fullname" . }}-ui
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  containers:
  - name: {{ template "kafka.name" . }}-kafka-manager
    image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
    imagePullPolicy: "{{ .Values.ui.image.pullPolicy }}"
    ports:
    - containerPort: 9000
      name: ui
    env:
    - name: ZK_HOSTS
      value: {{ .Release.Name }}-zookeeper:2181
    - name: APPLICATION_SECRET
      value: letmein
{{- end }}
