{{- if .Values.kafkacat.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "kafka.fullname" . }}-kafkacat
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    component: "{{ .Values.kafkacat.name }}"
    heritage: {{ .Release.Service | quote }}
spec:
  containers:
  - name: {{ template "kafka.name" . }}-kafkacat
    image: solsson/kafkacat@sha256:1266d140c52cb39bf314b6f22b6d7a01c4c9084781bc779fdfade51214a713a8
    command:
    - sh
    - -c
    - "exec tail -f /dev/null"
{{- end }}
