apiVersion: v1
kind: Pod
metadata:
  name: {{ template "kafka.fullname" . }}-cli
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  containers:
  - name: {{ template "kafka.name" . }}-cli
    image: solsson/kafka:0.11.0.0
    command:
    - sh
    - -c
    - "exec tail -f /dev/null"
