{{- if .Values.Metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}-exporter
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - name: exporter
    port: 5556
  selector:
    app: {{ include "kafka.name" . | quote }}
    release: {{ .Release.Name | quote }}
{{- end }}