kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: st1
