kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.name | quote }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Values.name | quote }}
      labels:
        name: {{ .Values.name | quote }}
    spec:
      containers:
      - name: {{ .Values.name | quote }}
        image: {{ .Values.image | quote }}
        imagePullPolicy: Always
        env:
{{ toYaml .Values.env | indent 10 }}
