# Name: The name assigned to all of the frontend objects defined in this template.
name: nodejs-example
# Docker image ref
image: ""
# Number of replicas
replicas: 1
# Environment variables
env:
  - name: NODE_ENV
    value: test
